-- Seed Michigan counties into us_counties table
-- This adds all 83 Michigan counties to enable vendor/rep coverage in MI

INSERT INTO public.us_counties (state_code, state_name, county_name) VALUES
('MI', 'Michigan', 'Alcona County'),
('MI', 'Michigan', 'Alger County'),
('MI', 'Michigan', 'Allegan County'),
('MI', 'Michigan', 'Alpena County'),
('MI', 'Michigan', 'Antrim County'),
('MI', 'Michigan', 'Arenac County'),
('MI', 'Michigan', 'Baraga County'),
('MI', 'Michigan', 'Barry County'),
('MI', 'Michigan', 'Bay County'),
('MI', 'Michigan', 'Benzie County'),
('MI', 'Michigan', 'Berrien County'),
('MI', 'Michigan', 'Branch County'),
('MI', 'Michigan', 'Calhoun County'),
('MI', 'Michigan', 'Cass County'),
('MI', 'Michigan', 'Charlevoix County'),
('MI', 'Michigan', 'Cheboygan County'),
('MI', 'Michigan', 'Chippewa County'),
('MI', 'Michigan', 'Clare County'),
('MI', 'Michigan', 'Clinton County'),
('MI', 'Michigan', 'Crawford County'),
('MI', 'Michigan', 'Delta County'),
('MI', 'Michigan', 'Dickinson County'),
('MI', 'Michigan', 'Eaton County'),
('MI', 'Michigan', 'Emmet County'),
('MI', 'Michigan', 'Genesee County'),
('MI', 'Michigan', 'Gladwin County'),
('MI', 'Michigan', 'Gogebic County'),
('MI', 'Michigan', 'Grand Traverse County'),
('MI', 'Michigan', 'Gratiot County'),
('MI', 'Michigan', 'Hillsdale County'),
('MI', 'Michigan', 'Houghton County'),
('MI', 'Michigan', 'Huron County'),
('MI', 'Michigan', 'Ingham County'),
('MI', 'Michigan', 'Ionia County'),
('MI', 'Michigan', 'Iosco County'),
('MI', 'Michigan', 'Iron County'),
('MI', 'Michigan', 'Isabella County'),
('MI', 'Michigan', 'Jackson County'),
('MI', 'Michigan', 'Kalamazoo County'),
('MI', 'Michigan', 'Kalkaska County'),
('MI', 'Michigan', 'Kent County'),
('MI', 'Michigan', 'Keweenaw County'),
('MI', 'Michigan', 'Lake County'),
('MI', 'Michigan', 'Lapeer County'),
('MI', 'Michigan', 'Leelanau County'),
('MI', 'Michigan', 'Lenawee County'),
('MI', 'Michigan', 'Livingston County'),
('MI', 'Michigan', 'Luce County'),
('MI', 'Michigan', 'Mackinac County'),
('MI', 'Michigan', 'Macomb County'),
('MI', 'Michigan', 'Manistee County'),
('MI', 'Michigan', 'Marquette County'),
('MI', 'Michigan', 'Mason County'),
('MI', 'Michigan', 'Mecosta County'),
('MI', 'Michigan', 'Menominee County'),
('MI', 'Michigan', 'Midland County'),
('MI', 'Michigan', 'Missaukee County'),
('MI', 'Michigan', 'Monroe County'),
('MI', 'Michigan', 'Montcalm County'),
('MI', 'Michigan', 'Montmorency County'),
('MI', 'Michigan', 'Muskegon County'),
('MI', 'Michigan', 'Newaygo County'),
('MI', 'Michigan', 'Oakland County'),
('MI', 'Michigan', 'Oceana County'),
('MI', 'Michigan', 'Ogemaw County'),
('MI', 'Michigan', 'Ontonagon County'),
('MI', 'Michigan', 'Osceola County'),
('MI', 'Michigan', 'Oscoda County'),
('MI', 'Michigan', 'Otsego County'),
('MI', 'Michigan', 'Ottawa County'),
('MI', 'Michigan', 'Presque Isle County'),
('MI', 'Michigan', 'Roscommon County'),
('MI', 'Michigan', 'Saginaw County'),
('MI', 'Michigan', 'Sanilac County'),
('MI', 'Michigan', 'Schoolcraft County'),
('MI', 'Michigan', 'Shiawassee County'),
('MI', 'Michigan', 'St. Clair County'),
('MI', 'Michigan', 'St. Joseph County'),
('MI', 'Michigan', 'Tuscola County'),
('MI', 'Michigan', 'Van Buren County'),
('MI', 'Michigan', 'Washtenaw County'),
('MI', 'Michigan', 'Wayne County'),
('MI', 'Michigan', 'Wexford County')
ON CONFLICT DO NOTHING;