-- Create us_counties reference table for validated county data
CREATE TABLE public.us_counties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  state_code text NOT NULL,
  state_name text NOT NULL,
  county_name text NOT NULL,
  county_fips text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.us_counties IS 'Reference table for validated US county data. Used to ensure clean coverage area entries in rep_coverage_areas.';
COMMENT ON COLUMN public.us_counties.state_code IS '2-letter state code (e.g., WI, IL)';
COMMENT ON COLUMN public.us_counties.county_name IS 'Full county name including "County" (e.g., Milwaukee County)';
COMMENT ON COLUMN public.us_counties.county_fips IS 'Optional FIPS code for future analytics';

-- Create index for fast lookups by state
CREATE INDEX idx_us_counties_state_code ON public.us_counties(state_code);

-- Seed Wisconsin counties (MVP)
INSERT INTO public.us_counties (state_code, state_name, county_name) VALUES
  ('WI', 'Wisconsin', 'Adams County'),
  ('WI', 'Wisconsin', 'Ashland County'),
  ('WI', 'Wisconsin', 'Barron County'),
  ('WI', 'Wisconsin', 'Bayfield County'),
  ('WI', 'Wisconsin', 'Brown County'),
  ('WI', 'Wisconsin', 'Buffalo County'),
  ('WI', 'Wisconsin', 'Burnett County'),
  ('WI', 'Wisconsin', 'Calumet County'),
  ('WI', 'Wisconsin', 'Chippewa County'),
  ('WI', 'Wisconsin', 'Clark County'),
  ('WI', 'Wisconsin', 'Columbia County'),
  ('WI', 'Wisconsin', 'Crawford County'),
  ('WI', 'Wisconsin', 'Dane County'),
  ('WI', 'Wisconsin', 'Dodge County'),
  ('WI', 'Wisconsin', 'Door County'),
  ('WI', 'Wisconsin', 'Douglas County'),
  ('WI', 'Wisconsin', 'Dunn County'),
  ('WI', 'Wisconsin', 'Eau Claire County'),
  ('WI', 'Wisconsin', 'Florence County'),
  ('WI', 'Wisconsin', 'Fond du Lac County'),
  ('WI', 'Wisconsin', 'Forest County'),
  ('WI', 'Wisconsin', 'Grant County'),
  ('WI', 'Wisconsin', 'Green County'),
  ('WI', 'Wisconsin', 'Green Lake County'),
  ('WI', 'Wisconsin', 'Iowa County'),
  ('WI', 'Wisconsin', 'Iron County'),
  ('WI', 'Wisconsin', 'Jackson County'),
  ('WI', 'Wisconsin', 'Jefferson County'),
  ('WI', 'Wisconsin', 'Juneau County'),
  ('WI', 'Wisconsin', 'Kenosha County'),
  ('WI', 'Wisconsin', 'Kewaunee County'),
  ('WI', 'Wisconsin', 'La Crosse County'),
  ('WI', 'Wisconsin', 'Lafayette County'),
  ('WI', 'Wisconsin', 'Langlade County'),
  ('WI', 'Wisconsin', 'Lincoln County'),
  ('WI', 'Wisconsin', 'Manitowoc County'),
  ('WI', 'Wisconsin', 'Marathon County'),
  ('WI', 'Wisconsin', 'Marinette County'),
  ('WI', 'Wisconsin', 'Marquette County'),
  ('WI', 'Wisconsin', 'Menominee County'),
  ('WI', 'Wisconsin', 'Milwaukee County'),
  ('WI', 'Wisconsin', 'Monroe County'),
  ('WI', 'Wisconsin', 'Oconto County'),
  ('WI', 'Wisconsin', 'Oneida County'),
  ('WI', 'Wisconsin', 'Outagamie County'),
  ('WI', 'Wisconsin', 'Ozaukee County'),
  ('WI', 'Wisconsin', 'Pepin County'),
  ('WI', 'Wisconsin', 'Pierce County'),
  ('WI', 'Wisconsin', 'Polk County'),
  ('WI', 'Wisconsin', 'Portage County'),
  ('WI', 'Wisconsin', 'Price County'),
  ('WI', 'Wisconsin', 'Racine County'),
  ('WI', 'Wisconsin', 'Richland County'),
  ('WI', 'Wisconsin', 'Rock County'),
  ('WI', 'Wisconsin', 'Rusk County'),
  ('WI', 'Wisconsin', 'Sauk County'),
  ('WI', 'Wisconsin', 'Sawyer County'),
  ('WI', 'Wisconsin', 'Shawano County'),
  ('WI', 'Wisconsin', 'Sheboygan County'),
  ('WI', 'Wisconsin', 'St. Croix County'),
  ('WI', 'Wisconsin', 'Taylor County'),
  ('WI', 'Wisconsin', 'Trempealeau County'),
  ('WI', 'Wisconsin', 'Vernon County'),
  ('WI', 'Wisconsin', 'Vilas County'),
  ('WI', 'Wisconsin', 'Walworth County'),
  ('WI', 'Wisconsin', 'Washburn County'),
  ('WI', 'Wisconsin', 'Washington County'),
  ('WI', 'Wisconsin', 'Waukesha County'),
  ('WI', 'Wisconsin', 'Waupaca County'),
  ('WI', 'Wisconsin', 'Waushara County'),
  ('WI', 'Wisconsin', 'Winnebago County'),
  ('WI', 'Wisconsin', 'Wood County');

-- Seed Illinois counties (MVP)
INSERT INTO public.us_counties (state_code, state_name, county_name) VALUES
  ('IL', 'Illinois', 'Adams County'),
  ('IL', 'Illinois', 'Alexander County'),
  ('IL', 'Illinois', 'Bond County'),
  ('IL', 'Illinois', 'Boone County'),
  ('IL', 'Illinois', 'Brown County'),
  ('IL', 'Illinois', 'Bureau County'),
  ('IL', 'Illinois', 'Calhoun County'),
  ('IL', 'Illinois', 'Carroll County'),
  ('IL', 'Illinois', 'Cass County'),
  ('IL', 'Illinois', 'Champaign County'),
  ('IL', 'Illinois', 'Christian County'),
  ('IL', 'Illinois', 'Clark County'),
  ('IL', 'Illinois', 'Clay County'),
  ('IL', 'Illinois', 'Clinton County'),
  ('IL', 'Illinois', 'Coles County'),
  ('IL', 'Illinois', 'Cook County'),
  ('IL', 'Illinois', 'Crawford County'),
  ('IL', 'Illinois', 'Cumberland County'),
  ('IL', 'Illinois', 'DeKalb County'),
  ('IL', 'Illinois', 'DeWitt County'),
  ('IL', 'Illinois', 'Douglas County'),
  ('IL', 'Illinois', 'DuPage County'),
  ('IL', 'Illinois', 'Edgar County'),
  ('IL', 'Illinois', 'Edwards County'),
  ('IL', 'Illinois', 'Effingham County'),
  ('IL', 'Illinois', 'Fayette County'),
  ('IL', 'Illinois', 'Ford County'),
  ('IL', 'Illinois', 'Franklin County'),
  ('IL', 'Illinois', 'Fulton County'),
  ('IL', 'Illinois', 'Gallatin County'),
  ('IL', 'Illinois', 'Greene County'),
  ('IL', 'Illinois', 'Grundy County'),
  ('IL', 'Illinois', 'Hamilton County'),
  ('IL', 'Illinois', 'Hancock County'),
  ('IL', 'Illinois', 'Hardin County'),
  ('IL', 'Illinois', 'Henderson County'),
  ('IL', 'Illinois', 'Henry County'),
  ('IL', 'Illinois', 'Iroquois County'),
  ('IL', 'Illinois', 'Jackson County'),
  ('IL', 'Illinois', 'Jasper County'),
  ('IL', 'Illinois', 'Jefferson County'),
  ('IL', 'Illinois', 'Jersey County'),
  ('IL', 'Illinois', 'Jo Daviess County'),
  ('IL', 'Illinois', 'Johnson County'),
  ('IL', 'Illinois', 'Kane County'),
  ('IL', 'Illinois', 'Kankakee County'),
  ('IL', 'Illinois', 'Kendall County'),
  ('IL', 'Illinois', 'Knox County'),
  ('IL', 'Illinois', 'Lake County'),
  ('IL', 'Illinois', 'LaSalle County'),
  ('IL', 'Illinois', 'Lawrence County'),
  ('IL', 'Illinois', 'Lee County'),
  ('IL', 'Illinois', 'Livingston County'),
  ('IL', 'Illinois', 'Logan County'),
  ('IL', 'Illinois', 'Macon County'),
  ('IL', 'Illinois', 'Macoupin County'),
  ('IL', 'Illinois', 'Madison County'),
  ('IL', 'Illinois', 'Marion County'),
  ('IL', 'Illinois', 'Marshall County'),
  ('IL', 'Illinois', 'Mason County'),
  ('IL', 'Illinois', 'Massac County'),
  ('IL', 'Illinois', 'McDonough County'),
  ('IL', 'Illinois', 'McHenry County'),
  ('IL', 'Illinois', 'McLean County'),
  ('IL', 'Illinois', 'Menard County'),
  ('IL', 'Illinois', 'Mercer County'),
  ('IL', 'Illinois', 'Monroe County'),
  ('IL', 'Illinois', 'Montgomery County'),
  ('IL', 'Illinois', 'Morgan County'),
  ('IL', 'Illinois', 'Moultrie County'),
  ('IL', 'Illinois', 'Ogle County'),
  ('IL', 'Illinois', 'Peoria County'),
  ('IL', 'Illinois', 'Perry County'),
  ('IL', 'Illinois', 'Piatt County'),
  ('IL', 'Illinois', 'Pike County'),
  ('IL', 'Illinois', 'Pope County'),
  ('IL', 'Illinois', 'Pulaski County'),
  ('IL', 'Illinois', 'Putnam County'),
  ('IL', 'Illinois', 'Randolph County'),
  ('IL', 'Illinois', 'Richland County'),
  ('IL', 'Illinois', 'Rock Island County'),
  ('IL', 'Illinois', 'Saline County'),
  ('IL', 'Illinois', 'Sangamon County'),
  ('IL', 'Illinois', 'Schuyler County'),
  ('IL', 'Illinois', 'Scott County'),
  ('IL', 'Illinois', 'Shelby County'),
  ('IL', 'Illinois', 'St. Clair County'),
  ('IL', 'Illinois', 'Stark County'),
  ('IL', 'Illinois', 'Stephenson County'),
  ('IL', 'Illinois', 'Tazewell County'),
  ('IL', 'Illinois', 'Union County'),
  ('IL', 'Illinois', 'Vermilion County'),
  ('IL', 'Illinois', 'Wabash County'),
  ('IL', 'Illinois', 'Warren County'),
  ('IL', 'Illinois', 'Washington County'),
  ('IL', 'Illinois', 'Wayne County'),
  ('IL', 'Illinois', 'White County'),
  ('IL', 'Illinois', 'Whiteside County'),
  ('IL', 'Illinois', 'Will County'),
  ('IL', 'Illinois', 'Williamson County'),
  ('IL', 'Illinois', 'Winnebago County'),
  ('IL', 'Illinois', 'Woodford County');

-- TODO: Expand to all US counties using a comprehensive JSON seed file

-- Update rep_coverage_areas table
ALTER TABLE public.rep_coverage_areas
  ADD COLUMN county_id uuid NULL REFERENCES public.us_counties(id) ON DELETE SET NULL,
  ADD COLUMN region_note text NULL;

COMMENT ON COLUMN public.rep_coverage_areas.county_id IS 'FK to us_counties for validated county data';
COMMENT ON COLUMN public.rep_coverage_areas.region_note IS 'Optional free-text note about this coverage region (e.g., "only metro area within 30 miles")';

-- Note: Existing county_name values are preserved as legacy data for manual cleanup later
COMMENT ON COLUMN public.rep_coverage_areas.county_name IS 'County name for display. Legacy free-text values should be matched to us_counties.county_name and linked via county_id.';

-- Enable RLS on us_counties (read-only for authenticated users)
ALTER TABLE public.us_counties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Counties are viewable by authenticated users"
  ON public.us_counties
  FOR SELECT
  USING (true);